Issues #125, 129, and 140
NewPath-Consulting/Wild-Apricot-Press pull request #169
Opened 2024-10-10 17:20 UTC by nataliebrotherton

Issue #125 turn on debug log by default
- Added a flag in the options table to store whether the user has changed the debug log setting
- If it hasn't been changed, debug log is enabled on activation

Issue #129 Validate correct authorized application
- Server application has access to 15 endpoints
- Wild Apricot API will respond with a list of scopes. If there are less than 15, the user is prompted to change the application type to a server application

Issue #140 Remove admin-only fields
- Admin-only fields are separated into another list stored in the options table and displayed as `disabled` or grayed out checkboxes

2024-10-10 18:42 UTC, asirota commented
I'll need to update read me file with changes. Can you also tag this as a 1.1 version please in the code?

2024-10-10 19:00 UTC, nataliebrotherton commented
did you want to wait for the rest of the issues to be resolved? (fixing sync, customizing login page, etc)

2024-10-10 19:35 UTC, asirota commented
> did you want to wait for the rest of the issues to be resolved? (fixing sync, customizing login page, etc)

I think so. You can keep doing to this draft PR. And I can test against it before merging.

2024-10-11 17:55 UTC, nataliebrotherton commented
This branch is named specific to the issues that were fixed so I made a 1.1 branch and set that as the upstream for this one

2024-10-11 18:19 UTC, asirota approved these changes

2024-10-11 18:20 UTC, asirota commented on src/admin-settings.php
WildApricot is spelled without the space always.

2024-10-11 18:21 UTC, asirota commented on src/admin-settings.php
> +        print 'Admin-only contact fields are displayed below the list of contact fields but are not available to sync. If you wish to sync these fields with your site please change the field settings
Wild Apricot should be WildApricot

2024-10-11 18:22 UTC, asirota commented on src/admin-settings.php
> +            echo '<p class="wap-error">Incorrect application scope. Please create a <strong>full-access Server Application</strong> on Wild Apricot.</p>';
WildApricot is the correct spelling

2024-10-11 18:26 UTC, asirota requested changes
just a few typos on WildApricot spelling

2024-10-11 18:37 UTC, asirota commented
> This branch is named specific to the issues that were fixed so I made a 1.1 branch and set that as the upstream for this one

Ok, this pull is set to go  against master so you probably want to change the target to 1.1

2024-10-15 14:41 UTC, asirota commented
@nataliebrotherton  please confirm the changes I requested and make the edits.

2024-10-15 16:09 UTC, asirota approved these changes

2024-10-15 16:10 UTC, merged