Fixing unsanitized fields
NewPath-Consulting/Wild-Apricot-Press pull request #66
Opened 2022-07-06 17:01 UTC by nataliebrotherton

* Sanitize `$_POST` in `post_access_load_restrictions`
* Remove use of `$_GET` in `MySettingsPage.php`

I addressed the examples included in the issue. I believe everything else should be sanitized correctly. Let me know if there's more.

2022-07-06 18:58 UTC, asirota commented on src/Addon.php
> +    const HOOK_URL = 'https://newpathconsulting.com/checkdev';
the production license checker will be at https://newpathconsulting.com/check

all active registered license keys will be at /check
all testing keys and some legacy keys will be at /checkdev

2022-07-06 19:00 UTC, asirota commented on src/Log.php
> +        $error_dir = '/Users/natalieb/dev/npc/error.log';
will this error directory be available on a target install? Maybe do something relative to where the plugin is running?

2022-07-06 19:01 UTC, asirota commented on plugin.php
> + * Version:           1.0b3
I updated the version in the comments to 1.0b3

2022-07-06 19:04 UTC, asirota requested changes
I left a few comments for you to double check, particularly the license checker URL... I left them as comments on the line of code.

2022-07-06 20:02 UTC, nataliebrotherton commented on src/Log.php
> +        $error_dir = '/Users/natalieb/dev/npc/error.log';
No it won't, this was just for my own personal use. I'm not sure if I could do this in production because the file has to be on the server side so that would depend on who's using it.

2022-07-06 20:12 UTC, nataliebrotherton commented on src/Log.php
> +        $error_dir = '/Users/natalieb/dev/npc/error.log';
My bad. I definitely should have removed this file for the beta 3 release. It won't be seen by users unless they go hunting in the files on their install or through the wordpress file editor. Taking note of this for next release.

2022-07-06 20:13 UTC, nataliebrotherton commented on src/Addon.php
> +    const HOOK_URL = 'https://newpathconsulting.com/checkdev';
Oops. I thought I had all the updates from beta 3. Sorry about that.

2022-07-06 20:19 UTC, nataliebrotherton commented on src/Log.php
> +        $error_dir = '/Users/natalieb/dev/npc/error.log';
Where should I go with this? I'll be needing this basically for as long as I'll be working on this plugin, so instead of removing it for every branch, I could remove it when we release a new version.

2022-07-06 20:50 UTC, asirota commented on src/Log.php
> +        $error_dir = '/Users/natalieb/dev/npc/error.log';
Why don't you move logging into a known debug.log file for WordPress?  [You can use the error logging feature in WordPress to see if WP_DEBUG](https://www.wpbeginner.com/wp-tutorials/how-to-find-and-access-wordpress-error-logs-step-by-step/) is turned on and stream errors to that file instead of your own error.log

2022-07-07 19:23 UTC, asirota approved these changes
looks great, Natalie! Thank you for doing the weblog change...

2022-07-07 19:24 UTC, merged