Cover sync options edge cases
NewPath-Consulting/Wild-Apricot-Press pull request #98
Opened 2022-08-15 18:34 UTC by nataliebrotherton

Closes #97 

- Reloads sync options every time the page is accessed to get most recent name changes or additions
- Clears stored contact fields and the checked contact fields when credentials are entered for a different WildApricot website

2022-08-15 20:26 UTC, asirota reviewed
I didn't change this Make.comdata structure in make so this probably won't work

2022-08-16 13:23 UTC, nataliebrotherton commented
> I didn't change this Make.comdata structure in make so this probably won't work
That's weird beause it wasn't working before I changed it and worked after.

2022-08-16 13:40 UTC, nataliebrotherton commented
@asirota This is what the Make response looks like
<img width="793" alt="Screen Shot 2022-08-16 at 9 39 38 AM" src="https://user-images.githubusercontent.com/25440470/184893814-394837d5-ac24-47d9-9ee0-1ab34ea107d5.png">

2022-08-16 13:44 UTC, asirota commented
I assume this is the development checker not prod?

2022-08-16 13:45 UTC, nataliebrotherton commented
@asirota Yes that's what I've been using. I see now that they're different.

2022-08-16 14:00 UTC, asirota commented
Yes I was trying out a data structure change on Make.com on the DEV license key checker. When I changed the data store's underlying datastructure the data disappeared as if I created new columns so I changed it back and the data came back into the data store. The change I made was to remove the spaces in the "Wild Apricot" part of the field names in the data store, and I reverted. Both prod and dev license checkers should return the original labels with "Wild Apricot" in them:

Dev example:
https://hook.us1.make.com/4suuck1up58qja9qfcqyosyhni63jwsn?key=UNEXPIRED-KEY-FOR-TESTING&json=1

2022-08-16 14:54 UTC, nataliebrotherton commented
@asirota Ok I will change them back.

2022-08-16 17:20 UTC, asirota commented
I had to adjust the scenario on the DEV license checker to make sure the previously named keys were added to the Create JSON module which somehow was caching the new key names (no space in WildApricot)... This should be ok now on the dev checker.

2022-08-20 15:24 UTC, asirota commented on src/class-wa-integration.php
> +			Log::wap_log_warning('License Wild Apricot IDs missing from hook response');
Wild Apricot -> WildApricot please

2022-08-20 15:24 UTC, asirota commented on src/class-wa-integration.php
> +			Log::wap_log_warning('Licensed Wild Apricot URLs missing from hook response.');
Wild Apricot -> WildApricot please

2022-08-20 15:25 UTC, asirota requested changes
a couple of small text changes

2022-08-24 17:30 UTC, asirota approved these changes

2022-08-24 17:30 UTC, merged